routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::view('/', 'auth.login')->middleware('guest');

Auth::routes();
Route::middleware('auth')->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    /*
     * ArtStudios Routes
     */
    Route::resource('art_studios', 'ArtStudioController');

    /*
     * TraditionalMusicInstruments Routes
     */
    Route::resource('traditional_music_instruments', 'TraditionalMusicInstrumentController');

    /*
     * TraditionalDances Routes
     */
    Route::resource('traditional_dances', 'TraditionalDanceController');

    /*
     * TraditionalCeremonies Routes
     */
    Route::resource('traditional_ceremonies', 'TraditionalCeremonyController');

    /*
     * RitualCeremonies Routes
     */
    Route::resource('ritual_ceremonies', 'RitualCeremonyController');

    /*
     * TraditionalGames Routes
     */
    Route::resource('traditional_games', 'TraditionalGameController');

    /*
     * CulturalHeritages Routes
     */
    Route::resource('cultural_heritages', 'CulturalHeritageController');

    /*
     * NaturalArtificialTourisms Routes
     */
    Route::resource('natural_artificial_tourisms', 'NaturalArtificialTourismController');

    /*
     * SubDistricts Routes
     */
    Route::resource('sub_districts', 'SubDistrictController');

    /*
     * ChangePassword Routes
     */
    Route::get('profile/update-password', 'ChangePasswordController@show')->name('profile.change_password.form');
    Route::post('profile/update-password', 'ChangePasswordController@update')->name('profile.change_password.update');

    /*
     * Backup Restore Database Routes
     */
    Route::post('backups/upload', ['as' => 'backups.upload', 'uses' => 'BackupsController@upload']);
    Route::post('backups/{fileName}/restore', ['as' => 'backups.restore', 'uses' => 'BackupsController@restore']);
    Route::get('backups/{fileName}/dl', ['as' => 'backups.download', 'uses' => 'BackupsController@download']);
    Route::resource('backups', 'BackupsController', ['except' => ['create', 'show', 'edit']]);

});

app/RitualCeremony.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class RitualCeremony extends Model
{
    protected $fillable = ['name', 'detail', 'description', 'creator_id'];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('ritual_ceremony.ritual_ceremony'),
        ]);
        $link = '<a href="'.route('ritual_ceremonies.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/RitualCeremonyController.php
<?php

namespace App\Http\Controllers;

use App\RitualCeremony;
use Illuminate\Http\Request;

class RitualCeremonyController extends Controller
{
    /**
     * Display a listing of the ritualCeremony.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $ritualCeremonyQuery = RitualCeremony::query();
        $ritualCeremonyQuery->where('name', 'like', '%'.request('q').'%');
        $ritualCeremonies = $ritualCeremonyQuery->paginate(25);

        return view('ritual_ceremonies.index', compact('ritualCeremonies'));
    }

    /**
     * Show the form for creating a new ritualCeremony.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', new RitualCeremony);

        return view('ritual_ceremonies.create');
    }

    /**
     * Store a newly created ritualCeremony in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new RitualCeremony);

        $newRitualCeremony = $request->validate([
            'name'        => 'required|max:60',
            'detail'      => 'required|max:255',
            'description' => 'nullable|max:255',
        ]);
        $newRitualCeremony['creator_id'] = auth()->id();

        $ritualCeremony = RitualCeremony::create($newRitualCeremony);

        flash(__('ritual_ceremony.created'), 'success');

        return redirect()->route('ritual_ceremonies.show', $ritualCeremony);
    }

    /**
     * Display the specified ritualCeremony.
     *
     * @param  \App\RitualCeremony  $ritualCeremony
     * @return \Illuminate\View\View
     */
    public function show(RitualCeremony $ritualCeremony)
    {
        return view('ritual_ceremonies.show', compact('ritualCeremony'));
    }

    /**
     * Show the form for editing the specified ritualCeremony.
     *
     * @param  \App\RitualCeremony  $ritualCeremony
     * @return \Illuminate\View\View
     */
    public function edit(RitualCeremony $ritualCeremony)
    {
        $this->authorize('update', $ritualCeremony);

        return view('ritual_ceremonies.edit', compact('ritualCeremony'));
    }

    /**
     * Update the specified ritualCeremony in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\RitualCeremony  $ritualCeremony
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, RitualCeremony $ritualCeremony)
    {
        $this->authorize('update', $ritualCeremony);

        $ritualCeremonyData = $request->validate([
            'name'        => 'required|max:60',
            'detail'      => 'required|max:255',
            'description' => 'nullable|max:255',
        ]);
        $ritualCeremony->update($ritualCeremonyData);

        flash(__('ritual_ceremony.updated'), 'information');

        return redirect()->route('ritual_ceremonies.show', $ritualCeremony);
    }

    /**
     * Remove the specified ritualCeremony from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\RitualCeremony  $ritualCeremony
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, RitualCeremony $ritualCeremony)
    {
        $this->authorize('delete', $ritualCeremony);

        $request->validate(['ritual_ceremony_id' => 'required']);

        if ($request->get('ritual_ceremony_id') == $ritualCeremony->id && $ritualCeremony->delete()) {
            flash(__('ritual_ceremony.deleted'), 'error');
            return redirect()->route('ritual_ceremonies.index');
        }

        return back();
    }
}

resources/views/ritual_ceremonies/create.blade.php
@extends('layouts.app')

@section('title', __('ritual_ceremony.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('ritual_ceremony.create') }}</div>
            <form method="POST" action="{{ route('ritual_ceremonies.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('ritual_ceremony.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="detail" class="form-label">{{ __('ritual_ceremony.detail') }} <span class="form-required">*</span></label>
                        <textarea id="detail" class="form-control{{ $errors->has('detail') ? ' is-invalid' : '' }}" name="detail" rows="4">{{ old('detail') }}</textarea>
                        {!! $errors->first('detail', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('ritual_ceremony.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('ritual_ceremony.create') }}" class="btn btn-success">
                    <a href="{{ route('ritual_ceremonies.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/ritual_ceremonies/edit.blade.php
@extends('layouts.app')

@section('title', __('ritual_ceremony.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $ritualCeremony)
        @can('delete', $ritualCeremony)
            <div class="card">
                <div class="card-header">{{ __('ritual_ceremony.delete') }}</div>
                <div class="card-body">
                    <label class="form-label text-primary">{{ __('ritual_ceremony.name') }}</label>
                    <p>{{ $ritualCeremony->name }}</p>
                    <label class="form-label text-primary">{{ __('ritual_ceremony.detail') }}</label>
                    <p>{{ $ritualCeremony->detail }}</p>
                    <label class="form-label text-primary">{{ __('ritual_ceremony.description') }}</label>
                    <p>{{ $ritualCeremony->description ?? '-' }}</p>
                    {!! $errors->first('ritual_ceremony_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('ritual_ceremony.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('ritual_ceremonies.destroy', $ritualCeremony) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="ritual_ceremony_id" type="hidden" value="{{ $ritualCeremony->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('ritual_ceremonies.edit', $ritualCeremony) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header">{{ __('ritual_ceremony.edit') }}</div>
            <form method="POST" action="{{ route('ritual_ceremonies.update', $ritualCeremony) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('ritual_ceremony.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $ritualCeremony->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="detail" class="form-label">{{ __('ritual_ceremony.detail') }} <span class="form-required">*</span></label>
                        <textarea id="detail" class="form-control{{ $errors->has('detail') ? ' is-invalid' : '' }}" name="detail" rows="4">{{ old('detail', $ritualCeremony->detail) }}</textarea>
                        {!! $errors->first('detail', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('ritual_ceremony.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $ritualCeremony->description) }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('ritual_ceremony.update') }}" class="btn btn-success">
                    <a href="{{ route('ritual_ceremonies.show', $ritualCeremony) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    @can('delete', $ritualCeremony)
                        <a href="{{ route('ritual_ceremonies.edit', [$ritualCeremony, 'action' => 'delete']) }}" id="del-ritual_ceremony-{{ $ritualCeremony->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    @endcan
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/ritual_ceremonies/index.blade.php
@extends('layouts.app')

@section('title', __('ritual_ceremony.list'))

@section('content')
<div class="d-print-none mb-3">
    <div class="float-right">
        @can('create', new App\RitualCeremony)
            <a href="{{ route('ritual_ceremonies.create') }}" class="btn btn-success">{{ __('ritual_ceremony.create') }}</a>
            <a href="" class="btn btn-danger" onclick="window.print()">{{ __('app.print') }}</a>
            <a href="{{ route('home') }}" class="btn btn-outline-secondary">{{ __('app.back_to_menu') }}</a>
        @endcan
    </div>
    <h3 class="page-title">{{ __('ritual_ceremony.list') }} | <small>{{ __('app.total') }} : {{ $ritualCeremonies->total() }} {{ __('ritual_ceremony.ritual_ceremony') }}</small></h3>
</div>
<div class="d-none d-print-block">
    <h5 class="text-center"><b>UPACARA RITUAL</b></h5>
    <h5 class="text-center"><b>KABUPATEN KAPUAS</b></h5><br>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="d-print-none card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="form-label">{{ __('ritual_ceremony.search') }}</label>
                        <input placeholder="{{ __('ritual_ceremony.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('ritual_ceremony.search') }}" class="btn btn-secondary">
                    <a href="{{ route('ritual_ceremonies.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th width="30" style="vertical-align: middle;" class="text-center">{{ __('app.table_no') }}</th>
                        <th width="100" style="vertical-align: middle;">{{ __('ritual_ceremony.name') }}</th>
                        <th width="100" style="vertical-align: middle;">{{ __('ritual_ceremony.detail') }}</th>
                        <th width="100" style="vertical-align: middle;">{{ __('ritual_ceremony.description') }}</th>
                        <th width="100" style="vertical-align: middle;" class="d-print-none text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($ritualCeremonies as $key => $ritualCeremony)
                    <tr>
                        <td class="text-center">{{ $ritualCeremonies->firstItem() + $key }}</td>
                        <td>{{ $ritualCeremony->name }}</td>
                        <td>{{ $ritualCeremony->detail }}</td>
                        <td>{{ $ritualCeremony->description ?? '-' }}</td>
                        <td class="d-print-none text-center">
                            @can('view', $ritualCeremony)
                                <a href="{{ route('ritual_ceremonies.show', $ritualCeremony) }}" id="show-ritual_ceremony-{{ $ritualCeremony->id }}">{{ __('app.show') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $ritualCeremonies->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

resources/views/ritual_ceremonies/show.blade.php
@extends('layouts.app')

@section('title', __('ritual_ceremony.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('ritual_ceremony.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        <tr><td>{{ __('ritual_ceremony.name') }}</td><td>{{ $ritualCeremony->name }}</td></tr>
                        <tr><td>{{ __('ritual_ceremony.detail') }}</td><td>{{ $ritualCeremony->detail }}</td></tr>
                        <tr><td>{{ __('ritual_ceremony.description') }}</td><td>{{ $ritualCeremony->description ?? '-' }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                @can('update', $ritualCeremony)
                    <a href="{{ route('ritual_ceremonies.edit', $ritualCeremony) }}" id="edit-ritual_ceremony-{{ $ritualCeremony->id }}" class="btn btn-warning">{{ __('ritual_ceremony.edit') }}</a>
                @endcan
                <a href="{{ route('ritual_ceremonies.index') }}" class="btn btn-link">{{ __('ritual_ceremony.back_to_index') }}</a>
            </div>
        </div>
    </div>
</div>
@endsection