routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::view('/', 'auth.login')->middleware('guest');

Auth::routes();
Route::middleware('auth')->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    /*
     * ArtStudios Routes
     */
    Route::resource('art_studios', 'ArtStudioController');

    /*
     * TraditionalMusicInstruments Routes
     */
    Route::resource('traditional_music_instruments', 'TraditionalMusicInstrumentController');

    /*
     * TraditionalDances Routes
     */
    Route::resource('traditional_dances', 'TraditionalDanceController');

    /*
     * TraditionalCeremonies Routes
     */
    Route::resource('traditional_ceremonies', 'TraditionalCeremonyController');

    /*
     * RitualCeremonies Routes
     */
    Route::resource('ritual_ceremonies', 'RitualCeremonyController');

    /*
     * TraditionalGames Routes
     */
    Route::resource('traditional_games', 'TraditionalGameController');

    /*
     * CulturalHeritages Routes
     */
    Route::resource('cultural_heritages', 'CulturalHeritageController');

    /*
     * NaturalArtificialTourisms Routes
     */
    Route::resource('natural_artificial_tourisms', 'NaturalArtificialTourismController');

    /*
     * SubDistricts Routes
     */
    Route::resource('sub_districts', 'SubDistrictController');

    /*
     * ChangePassword Routes
     */
    Route::get('profile/update-password', 'ChangePasswordController@show')->name('profile.change_password.form');
    Route::post('profile/update-password', 'ChangePasswordController@update')->name('profile.change_password.update');

    /*
     * Backup Restore Database Routes
     */
    Route::post('backups/upload', ['as' => 'backups.upload', 'uses' => 'BackupsController@upload']);
    Route::post('backups/{fileName}/restore', ['as' => 'backups.restore', 'uses' => 'BackupsController@restore']);
    Route::get('backups/{fileName}/dl', ['as' => 'backups.download', 'uses' => 'BackupsController@download']);
    Route::resource('backups', 'BackupsController', ['except' => ['create', 'show', 'edit']]);

});

app/NaturalArtificialTourism.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class NaturalArtificialTourism extends Model
{
    protected $fillable = ['name', 'category', 'location', 'description', 'creator_id'];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('natural_artificial_tourism.natural_artificial_tourism'),
        ]);
        $link = '<a href="'.route('natural_artificial_tourisms.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/NaturalArtificialTourismController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\NaturalArtificialTourism;

class NaturalArtificialTourismController extends Controller
{
    /**
     * Display a listing of the naturalArtificialTourism.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $naturalArtificialTourismQuery = NaturalArtificialTourism::query();
        $naturalArtificialTourismQuery->where('name', 'like', '%'.request('q').'%');
        $naturalArtificialTourisms = $naturalArtificialTourismQuery->paginate(25);

        return view('natural_artificial_tourisms.index', compact('naturalArtificialTourisms'));
    }

    /**
     * Show the form for creating a new naturalArtificialTourism.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', new NaturalArtificialTourism);

        return view('natural_artificial_tourisms.create');
    }

    /**
     * Store a newly created naturalArtificialTourism in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new NaturalArtificialTourism);

        $newNaturalArtificialTourism = $request->validate([
            'name'        => 'required|max:60',
            'category'    => 'required|boolean',
            'location'    => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $newNaturalArtificialTourism['creator_id'] = auth()->id();

        $naturalArtificialTourism = NaturalArtificialTourism::create($newNaturalArtificialTourism);

        flash(__('natural_artificial_tourism.created'), 'success');

        return redirect()->route('natural_artificial_tourisms.show', $naturalArtificialTourism);
    }

    /**
     * Display the specified naturalArtificialTourism.
     *
     * @param  \App\NaturalArtificialTourism  $naturalArtificialTourism
     * @return \Illuminate\View\View
     */
    public function show(NaturalArtificialTourism $naturalArtificialTourism)
    {
        return view('natural_artificial_tourisms.show', compact('naturalArtificialTourism'));
    }

    /**
     * Show the form for editing the specified naturalArtificialTourism.
     *
     * @param  \App\NaturalArtificialTourism  $naturalArtificialTourism
     * @return \Illuminate\View\View
     */
    public function edit(NaturalArtificialTourism $naturalArtificialTourism)
    {
        $this->authorize('update', $naturalArtificialTourism);

        return view('natural_artificial_tourisms.edit', compact('naturalArtificialTourism'));
    }

    /**
     * Update the specified naturalArtificialTourism in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\NaturalArtificialTourism  $naturalArtificialTourism
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, NaturalArtificialTourism $naturalArtificialTourism)
    {
        $this->authorize('update', $naturalArtificialTourism);

        $naturalArtificialTourismData = $request->validate([
            'name'        => 'required|max:60',
            'category'    => 'required|boolean',
            'location'    => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $naturalArtificialTourism->update($naturalArtificialTourismData);

        flash(__('natural_artificial_tourism.updated'), 'information');

        return redirect()->route('natural_artificial_tourisms.show', $naturalArtificialTourism);
    }

    /**
     * Remove the specified naturalArtificialTourism from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\NaturalArtificialTourism  $naturalArtificialTourism
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, NaturalArtificialTourism $naturalArtificialTourism)
    {
        $this->authorize('delete', $naturalArtificialTourism);

        $request->validate(['natural_artificial_tourism_id' => 'required']);

        if ($request->get('natural_artificial_tourism_id') == $naturalArtificialTourism->id && $naturalArtificialTourism->delete()) {
            flash(__('natural_artificial_tourism.deleted'), 'error');
            return redirect()->route('natural_artificial_tourisms.index');
        }

        return back();
    }
}

resources/views/natural_artificial_tourisms/create.blade.php
@extends('layouts.app')

@section('title', __('natural_artificial_tourism.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('natural_artificial_tourism.create') }}</div>
            <form method="POST" action="{{ route('natural_artificial_tourisms.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('natural_artificial_tourism.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="category" class="form-label">{{ __('natural_artificial_tourism.category') }} <span class="form-required">*</span></label>
                        <div class="col-md-6">
                            <input type="radio" name="category" value="0" checked="true"> Wisata Alam <br>
                            <input type="radio" name="category" value="1"> Wisata Buatan <br>
                        </div>
                        {!! $errors->first('category', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="location" class="form-label">{{ __('natural_artificial_tourism.location') }} <span class="form-required">*</span></label>
                        <input id="location" type="text" class="form-control{{ $errors->has('location') ? ' is-invalid' : '' }}" name="location" value="{{ old('location') }}" required>
                        {!! $errors->first('location', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('natural_artificial_tourism.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('natural_artificial_tourism.create') }}" class="btn btn-success">
                    <a href="{{ route('natural_artificial_tourisms.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/natural_artificial_tourisms/edit.blade.php
@extends('layouts.app')

@section('title', __('natural_artificial_tourism.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $naturalArtificialTourism)
        @can('delete', $naturalArtificialTourism)
            <div class="card">
                <div class="card-header">{{ __('natural_artificial_tourism.delete') }}</div>
                <div class="card-body">
                    <label class="form-label text-primary">{{ __('natural_artificial_tourism.name') }}</label>
                    <p>{{ $naturalArtificialTourism->name }}</p>
                    <label class="form-label text-primary">{{ __('natural_artificial_tourism.category') }}</label>
                    <p>{{ $naturalArtificialTourism->category == 0 ? 'Wisata Alam' : 'Wisata Buatan' }}</p>
                    <label class="form-label text-primary">{{ __('natural_artificial_tourism.location') }}</label>
                    <p>{{ $naturalArtificialTourism->location }}</p>
                    <label class="form-label text-primary">{{ __('natural_artificial_tourism.description') }}</label>
                    <p>{{ $naturalArtificialTourism->description ?? '-' }}</p>
                    {!! $errors->first('natural_artificial_tourism_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('natural_artificial_tourism.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('natural_artificial_tourisms.destroy', $naturalArtificialTourism) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="natural_artificial_tourism_id" type="hidden" value="{{ $naturalArtificialTourism->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('natural_artificial_tourisms.edit', $naturalArtificialTourism) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header">{{ __('natural_artificial_tourism.edit') }}</div>
            <form method="POST" action="{{ route('natural_artificial_tourisms.update', $naturalArtificialTourism) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="form-label">{{ __('natural_artificial_tourism.name') }} <span class="form-required">*</span></label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $naturalArtificialTourism->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="category" class="form-label">{{ __('natural_artificial_tourism.category') }} <span class="form-required">*</span></label>
                        <div class="col-md-6">
                            <input type="radio" name="category" value="0" {{ $naturalArtificialTourism->category == 0 ? 'checked' : '' }}> Wisata Alam <br>
                            <input type="radio" name="category" value="1" {{ $naturalArtificialTourism->category == 1 ? 'checked' : '' }}> Wisata Buatan <br>
                        </div>
                        {!! $errors->first('category', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="location" class="form-label">{{ __('natural_artificial_tourism.location') }} <span class="form-required">*</span></label>
                        <input id="location" type="text" class="form-control{{ $errors->has('location') ? ' is-invalid' : '' }}" name="location" value="{{ old('location', $naturalArtificialTourism->location) }}" required>
                        {!! $errors->first('location', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="description" class="form-label">{{ __('natural_artificial_tourism.description') }}</label>
                        <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $naturalArtificialTourism->description) }}</textarea>
                        {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('natural_artificial_tourism.update') }}" class="btn btn-success">
                    <a href="{{ route('natural_artificial_tourisms.show', $naturalArtificialTourism) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    @can('delete', $naturalArtificialTourism)
                        <a href="{{ route('natural_artificial_tourisms.edit', [$naturalArtificialTourism, 'action' => 'delete']) }}" id="del-natural_artificial_tourism-{{ $naturalArtificialTourism->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    @endcan
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

resources/views/natural_artificial_tourisms/index.blade.php
@extends('layouts.app')

@section('title', __('natural_artificial_tourism.list'))

@section('content')
<div class="d-print-none mb-3">
    <div class="float-right">
        @can('create', new App\NaturalArtificialTourism)
            <a href="{{ route('natural_artificial_tourisms.create') }}" class="btn btn-success">{{ __('natural_artificial_tourism.create') }}</a>
            <a href="" class="btn btn-danger" onclick="window.print()">{{ __('app.print') }}</a>
            <a href="{{ route('home') }}" class="btn btn-outline-secondary">{{ __('app.back_to_menu') }}</a>
        @endcan
    </div>
    <h3 class="page-title">{{ __('natural_artificial_tourism.list') }} | <small>{{ __('app.total') }} : {{ $naturalArtificialTourisms->total() }} {{ __('natural_artificial_tourism.natural_artificial_tourism') }}</small></h3>
</div>
<div class="d-none d-print-block">
    <h5 class="text-center"><b>DATA OBJEK WISATA ALAM DAN BUATAN</b></h5>
    <h5 class="text-center"><b>KABUPATEN KAPUAS</b></h5><br>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="d-print-none card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="form-label">{{ __('natural_artificial_tourism.search') }}</label>
                        <input placeholder="{{ __('natural_artificial_tourism.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('natural_artificial_tourism.search') }}" class="btn btn-secondary">
                    <a href="{{ route('natural_artificial_tourisms.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('natural_artificial_tourism.name') }}</th>
                        <th>{{ __('natural_artificial_tourism.category') }}</th>
                        <th>{{ __('natural_artificial_tourism.location') }}</th>
                        <th>{{ __('natural_artificial_tourism.description') }}</th>
                        <th class="d-print-none text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($naturalArtificialTourisms as $key => $naturalArtificialTourism)
                    <tr>
                        <td class="text-center">{{ $naturalArtificialTourisms->firstItem() + $key }}</td>
                        <td>{{ $naturalArtificialTourism->name }}</td>
                        <td>{{ $naturalArtificialTourism->category == 0 ? 'Wisata Alam' : 'Wisata Buatan' }}</td>
                        <td>{{ $naturalArtificialTourism->location }}</td>
                        <td>{{ $naturalArtificialTourism->description ?? '-' }}</td>
                        <td class="d-print-none text-center">
                            @can('view', $naturalArtificialTourism)
                                <a href="{{ route('natural_artificial_tourisms.show', $naturalArtificialTourism) }}" id="show-natural_artificial_tourism-{{ $naturalArtificialTourism->id }}">{{ __('app.show') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $naturalArtificialTourisms->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

resources/views/natural_artificial_tourisms/show.blade.php
@extends('layouts.app')

@section('title', __('natural_artificial_tourism.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('natural_artificial_tourism.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        <tr><td>{{ __('natural_artificial_tourism.name') }}</td><td>{{ $naturalArtificialTourism->name }}</td></tr>
                        <tr><td>{{ __('natural_artificial_tourism.category') }}</td><td>{{ $naturalArtificialTourism->category == 0 ? 'Wisata Alam' : 'Wisata Buatan' }}</td></tr>
                        <tr><td>{{ __('natural_artificial_tourism.location') }}</td><td>{{ $naturalArtificialTourism->location }}</td></tr>
                        <tr><td>{{ __('natural_artificial_tourism.description') }}</td><td>{{ $naturalArtificialTourism->description ?? '-' }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                @can('update', $naturalArtificialTourism)
                    <a href="{{ route('natural_artificial_tourisms.edit', $naturalArtificialTourism) }}" id="edit-natural_artificial_tourism-{{ $naturalArtificialTourism->id }}" class="btn btn-warning">{{ __('natural_artificial_tourism.edit') }}</a>
                @endcan
                <a href="{{ route('natural_artificial_tourisms.index') }}" class="btn btn-link">{{ __('natural_artificial_tourism.back_to_index') }}</a>
            </div>
        </div>
    </div>
</div>
@endsection