routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::view('/', 'auth.login')->middleware('guest');

Auth::routes();
Route::middleware('auth')->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    /*
     * ArtStudios Routes
     */
    Route::resource('art_studios', 'ArtStudioController');

    /*
     * TraditionalMusicInstruments Routes
     */
    Route::resource('traditional_music_instruments', 'TraditionalMusicInstrumentController');

    /*
     * TraditionalDances Routes
     */
    Route::resource('traditional_dances', 'TraditionalDanceController');

    /*
     * TraditionalCeremonies Routes
     */
    Route::resource('traditional_ceremonies', 'TraditionalCeremonyController');

    /*
     * RitualCeremonies Routes
     */
    Route::resource('ritual_ceremonies', 'RitualCeremonyController');

    /*
     * TraditionalGames Routes
     */
    Route::resource('traditional_games', 'TraditionalGameController');

    /*
     * CulturalHeritages Routes
     */
    Route::resource('cultural_heritages', 'CulturalHeritageController');

    /*
     * NaturalArtificialTourisms Routes
     */
    Route::resource('natural_artificial_tourisms', 'NaturalArtificialTourismController');

    /*
     * SubDistricts Routes
     */
    Route::resource('sub_districts', 'SubDistrictController');

    /*
     * ChangePassword Routes
     */
    Route::get('profile/update-password', 'ChangePasswordController@show')->name('profile.change_password.form');
    Route::post('profile/update-password', 'ChangePasswordController@update')->name('profile.change_password.update');

    /*
     * Backup Restore Database Routes
     */
    Route::post('backups/upload', ['as' => 'backups.upload', 'uses' => 'BackupsController@upload']);
    Route::post('backups/{fileName}/restore', ['as' => 'backups.restore', 'uses' => 'BackupsController@restore']);
    Route::get('backups/{fileName}/dl', ['as' => 'backups.download', 'uses' => 'BackupsController@download']);
    Route::resource('backups', 'BackupsController', ['except' => ['create', 'show', 'edit']]);

});

app/SubDistrict.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class SubDistrict extends Model
{
    protected $fillable = ['name', 'description', 'creator_id'];

    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('sub_district.sub_district'),
        ]);
        $link = '<a href="'.route('sub_districts.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    public function creator()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/SubDistrictController.php
<?php

namespace App\Http\Controllers;

use App\SubDistrict;
use Illuminate\Http\Request;

class SubDistrictController extends Controller
{
    /**
     * Display a listing of the subDistrict.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $editableSubDistrict = null;
        $subDistrictQuery = SubDistrict::query();
        $subDistrictQuery->where('name', 'like', '%'.request('q').'%');
        $subDistricts = $subDistrictQuery->paginate(25);

        if (in_array(request('action'), ['edit', 'delete']) && request('id') != null) {
            $editableSubDistrict = SubDistrict::find(request('id'));
        }

        return view('sub_districts.index', compact('subDistricts', 'editableSubDistrict'));
    }

    /**
     * Store a newly created subDistrict in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new SubDistrict);

        $newSubDistrict = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $newSubDistrict['creator_id'] = auth()->id();

        SubDistrict::create($newSubDistrict);

        return redirect()->route('sub_districts.index');
    }

    /**
     * Update the specified subDistrict in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubDistrict  $subDistrict
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, SubDistrict $subDistrict)
    {
        $this->authorize('update', $subDistrict);

        $subDistrictData = $request->validate([
            'name'        => 'required|max:60',
            'description' => 'nullable|max:255',
        ]);
        $subDistrict->update($subDistrictData);

        $routeParam = request()->only('page', 'q');

        return redirect()->route('sub_districts.index', $routeParam);
    }

    /**
     * Remove the specified subDistrict from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubDistrict  $subDistrict
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, SubDistrict $subDistrict)
    {
        $this->authorize('delete', $subDistrict);

        $request->validate(['sub_district_id' => 'required']);

        if ($request->get('sub_district_id') == $subDistrict->id && $subDistrict->delete()) {
            $routeParam = request()->only('page', 'q');

            return redirect()->route('sub_districts.index', $routeParam);
        }

        return back();
    }
}

resources/views/sub_districts/forms.blade.php
@if (Request::get('action') == 'create')
@can('create', new App\SubDistrict)
    <form method="POST" action="{{ route('sub_districts.store') }}" accept-charset="UTF-8">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="name" class="form-label">{{ __('sub_district.name') }} <span class="form-required">*</span></label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <div class="form-group">
            <label for="description" class="form-label">{{ __('sub_district.description') }}</label>
            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description') }}</textarea>
            {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <input type="submit" value="{{ __('sub_district.create') }}" class="btn btn-success">
        <a href="{{ route('sub_districts.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
    </form>
@endcan
@endif
@if (Request::get('action') == 'edit' && $editableSubDistrict)
@can('update', $editableSubDistrict)
    <form method="POST" action="{{ route('sub_districts.update', $editableSubDistrict) }}" accept-charset="UTF-8">
        {{ csrf_field() }} {{ method_field('patch') }}
        <div class="form-group">
            <label for="name" class="form-label">{{ __('sub_district.name') }} <span class="form-required">*</span></label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $editableSubDistrict->name) }}" required>
            {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <div class="form-group">
            <label for="description" class="form-label">{{ __('sub_district.description') }}</label>
            <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" rows="4">{{ old('description', $editableSubDistrict->description) }}</textarea>
            {!! $errors->first('description', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <input name="page" value="{{ request('page') }}" type="hidden">
        <input name="q" value="{{ request('q') }}" type="hidden">
        <input type="submit" value="{{ __('sub_district.update') }}" class="btn btn-success">
        <a href="{{ route('sub_districts.index', Request::only('q', 'page')) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
        @can('delete', $editableSubDistrict)
            <a href="{{ route('sub_districts.index', ['action' => 'delete', 'id' => $editableSubDistrict->id] + Request::only('page', 'q')) }}" id="del-sub_district-{{ $editableSubDistrict->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
        @endcan
    </form>
@endcan
@endif
@if (Request::get('action') == 'delete' && $editableSubDistrict)
@can('delete', $editableSubDistrict)
    <div class="card">
        <div class="card-header">{{ __('sub_district.delete') }}</div>
        <div class="card-body">
            <label class="form-label text-primary">{{ __('sub_district.name') }}</label>
            <p>{{ $editableSubDistrict->name }}</p>
            <label class="form-label text-primary">{{ __('sub_district.description') }}</label>
            <p>{{ $editableSubDistrict->description }}</p>
            {!! $errors->first('sub_district_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
        </div>
        <hr style="margin:0">
        <div class="card-body text-danger">{{ __('sub_district.delete_confirm') }}</div>
        <div class="card-footer">
            <form method="POST" action="{{ route('sub_districts.destroy', $editableSubDistrict) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                {{ csrf_field() }} {{ method_field('delete') }}
                <input name="sub_district_id" type="hidden" value="{{ $editableSubDistrict->id }}">
                <input name="page" value="{{ request('page') }}" type="hidden">
                <input name="q" value="{{ request('q') }}" type="hidden">
                <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
            </form>
            <a href="{{ route('sub_districts.index', Request::only('q', 'page')) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
        </div>
    </div>
@endcan
@endif

resources/views/sub_districts/index.blade.php
@extends('layouts.app')

@section('title', __('sub_district.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
        @can('create', new App\SubDistrict)
            <a href="{{ route('sub_districts.index', ['action' => 'create']) }}" class="btn btn-success">{{ __('sub_district.create') }}</a>
            <a href="{{ route('home') }}" class="btn btn-outline-secondary">{{ __('app.back_to_menu') }}</a>
        @endcan
    </div>
    <h1 class="page-title">{{ __('sub_district.list') }} <small>{{ __('app.total') }} : {{ $subDistricts->total() }} {{ __('sub_district.sub_district') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="form-label">{{ __('sub_district.search') }}</label>
                        <input placeholder="{{ __('sub_district.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('sub_district.search') }}" class="btn btn-secondary">
                    <a href="{{ route('sub_districts.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm table-hover">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('sub_district.name') }}</th>
                        <th>{{ __('sub_district.description') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($subDistricts as $key => $subDistrict)
                    <tr>
                        <td class="text-center">{{ $subDistricts->firstItem() + $key }}</td>
                        <td>{{ $subDistrict->name }}</td>
                        <td>{{ $subDistrict->description }}</td>
                        <td class="text-center">
                            @can('update', $subDistrict)
                                <a href="{{ route('sub_districts.index', ['action' => 'edit', 'id' => $subDistrict->id] + Request::only('page', 'q')) }}" id="edit-sub_district-{{ $subDistrict->id }}">{{ __('app.edit') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $subDistricts->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
    <div class="col-md-4">
        @if(Request::has('action'))
        @include('sub_districts.forms')
        @endif
    </div>
</div>
@endsection