routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::view('/', 'auth.login')->middleware('guest');

Auth::routes();
Route::middleware('auth')->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    /*
     * ArtStudios Routes
     */
    Route::resource('art_studios', 'ArtStudioController');

    /*
     * TraditionalMusicInstruments Routes
     */
    Route::resource('traditional_music_instruments', 'TraditionalMusicInstrumentController');

    /*
     * TraditionalDances Routes
     */
    Route::resource('traditional_dances', 'TraditionalDanceController');

    /*
     * TraditionalCeremonies Routes
     */
    Route::resource('traditional_ceremonies', 'TraditionalCeremonyController');

    /*
     * RitualCeremonies Routes
     */
    Route::resource('ritual_ceremonies', 'RitualCeremonyController');

    /*
     * TraditionalGames Routes
     */
    Route::resource('traditional_games', 'TraditionalGameController');

    /*
     * CulturalHeritages Routes
     */
    Route::resource('cultural_heritages', 'CulturalHeritageController');

    /*
     * NaturalArtificialTourisms Routes
     */
    Route::resource('natural_artificial_tourisms', 'NaturalArtificialTourismController');

    /*
     * SubDistricts Routes
     */
    Route::resource('sub_districts', 'SubDistrictController');

    /*
     * ChangePassword Routes
     */
    Route::get('profile/update-password', 'ChangePasswordController@show')->name('profile.change_password.form');
    Route::post('profile/update-password', 'ChangePasswordController@update')->name('profile.change_password.update');

    /*
     * Backup Restore Database Routes
     */
    Route::post('backups/upload', ['as' => 'backups.upload', 'uses' => 'BackupsController@upload']);
    Route::post('backups/{fileName}/restore', ['as' => 'backups.restore', 'uses' => 'BackupsController@restore']);
    Route::get('backups/{fileName}/dl', ['as' => 'backups.download', 'uses' => 'BackupsController@download']);
    Route::resource('backups', 'BackupsController', ['except' => ['create', 'show', 'edit']]);

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/font-awesome-4.7.0/css/font-awesome.css') }}">

    <style>
    .icon_dashboard {
        color: white;
    }
    </style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <i class="fa fa-bars"></i> {{ __('app.menu_list') }} <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('art_studios.index') }}">{{ __('art_studio.list') }}</a>
                                    <a class="dropdown-item" href="{{ route('traditional_music_instruments.index') }}">{{ __('traditional_music_instrument.list') }}</a>
                                    <a class="dropdown-item" href="{{ route('traditional_dances.index') }}">{{ __('traditional_dance.list') }}</a>
                                    <a class="dropdown-item" href="{{ route('traditional_ceremonies.index') }}">{{ __('traditional_ceremony.list') }}</a>
                                    <a class="dropdown-item" href="{{ route('ritual_ceremonies.index') }}">{{ __('ritual_ceremony.list') }}</a>
                                    <a class="dropdown-item" href="{{ route('traditional_games.index') }}">{{ __('traditional_game.list') }}</a>
                                    <a class="dropdown-item" href="{{ route('cultural_heritages.index') }}">{{ __('cultural_heritage.list') }}</a>
                                    <a class="dropdown-item" href="{{ route('natural_artificial_tourisms.index') }}">{{ __('natural_artificial_tourism.list') }}</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <i class="fa fa-cogs"></i> {{ __('app.setting') }} <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('sub_districts.index') }}">{{ __('sub_district.list') }}</a>
                                    <a class="dropdown-item" href="{{ route('backups.index') }}">{{ __('backup.list')}}</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <i class="fa fa-user"></i> {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('profile.change_password.form') }}">{{ __('auth.change_password') }}</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4 container">
            @yield('content')
        </main>
    </div>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    @include('layouts.partials.noty')
</body>
</html>